apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-1-duo
  name: nginx-1-duo
  namespace: cka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-1-duo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-1-duo
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        resources: {}
status: {}
