apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx-2-duo
  name: nginx-2-duo
  namespace: cka
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-2-duo
  type: ClusterIP
status:
  loadBalancer: {}
